const actionTypes = {
  LOGIN: "LOGIN",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",

  GET_POSTS: "GET_POSTS",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_FAIL: "GET_POSTS_FAIL",

  GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
  GET_NEW_POSTS: "GET_NEW_POSTS",

  GET_CATEGORIES: "GET_CATEGORIES",
  GET_ACREAGES: "GET_ACREAGES",
  GET_PRICES: "GET_PRICES",

  GET_CURRENT_USER: "GET_CURRENT_USER",
  UPDATE_USER: "UPDATE_USER"
  
};

export default actionTypes;
